name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: clone repo 
      run: git clone https://github.com/ebquhf/github-actions-katas.git
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: ./github-actions-katas
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
       name: code
       path: .
    - name: test-step 
      run: ./ci/unit-test-app.sh
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
       name: code
       path: .
    - uses: actions/checkout@v2
    - name: build-step 
      run: ci/build-app.sh
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .