name: Java CI
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: clone repo 
      run: git clone https://github.com/ebquhf/github-actions-katas.git
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: ./github-actions-katas
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
       name: code
       path: .
    - name: test-step 
      run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
       name: code
       path: .
    - uses: actions/checkout@v2
    - name: build-step 
      run:  chmod +x ci/build-app.sh && ci/build-app.sh
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
  Docker-Image:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [Build,Test]
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
       name: code
       path: .
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.docker_username }}
        password: ${{ env.docker_password }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ebquhf/sdu_summer_school:latest

